### PR TITLE
SS-501 improve wiki integration

### PR DESCRIPTION
**Pull request by akochari**
## Status

- [ ] Ready
- [x] Draft
- [ ] Hold

## Description

Replaces the base template for django-wiki. Now we are using our own template (on top of `base.html`) to create the top of the guide pages (breadcrumbs, general menu) and sidebar whereas the content of the pages is generated by django-wiki templates. The sidebar links all pages in the guide/wiki.
Relates to issue SS-501.

## Types of changes

What types of changes does your code introduce to STACKn?

- [ ] Hotfix (fixing a critical bug in production)
- [ ] Bugfix
- [x] New feature
- [ ] Documentation update

## Checklist

_If you're unsure about any of the items below, don't hesitate to ask. We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [x] This pull request is against **develop** branch (not applicable for hotfixes)
- [x] I have included a link to the issue on GitHub or JIRA (if any)
- [ ] I have included migration files (if there are changes to the model classes)
- [x] I have included, reviewed and executed tests (unit and end2end) to complement my changes
- [ ] I have updated the related documentation (if necessary)
- [ ] I have updated the release notes (releasenotes.md)
- [x] I have added a reviewer for this pull request
- [x] I have added myself as an author for this pull request
- [ ] In the case I have modified settings.py, then I have also updated the studio-settings-configmap.yaml file in serve-charts

### CODE REVIEW

**Review by alfredeen — APPROVED** [review]
Nice work. It looks good to me.

**Review by churnikov — APPROVED** [review]
Haven't tried it locally, but lgtm

**Review by sandstromviktor — APPROVED** [review]
Works great! Tested locally and i works fine! I have some thoughts about the layout (distances between buttons, colors etc), but i believe that's another PR. Good job!

**Comment by akochari** [comment]
> Works great! Tested locally and i works fine! I have some thoughts about the layout (distances between buttons, colors etc), but i believe that's another PR. Good job!

Great, I'll be happy if you go in and suggest changes in that. Just like with the project layout. We do this later then, merging for now.

**Pull request merged**
